[package]
name = "cs_coursework"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = "0.28.0"
rand = "0.8.5"
sha256 = "1.1.1"

[dependencies.rocket]
version = "0.5.0-rc.2"
features = ["json", "tls"]