[package]
name = "cs_coursework"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
sha256 = "1.1.1"
sqlx = { version = "0.7.1", features = ["macros", "sqlite", "runtime-tokio"] }

[dependencies.rocket]
version = "0.5.0-rc.2"
features = ["json", "tls"]
